### ISSUE TITLE
about your app butyful

### ISSUE THREAD

**Issue by rizalamhadi** [sanket-vanani/final-butyful#1]
hello brother, Could you do me a favor? I will know, what this application is?
and what is "flgIsAccess" in your MySQL database?

**Comment by sanket-vanani** [comment]
Yes, This app is basically for production management based on the different production unit.  

This application is having role-based authentication and have different module...So the flgIsAccess value is 1 then that users have access to that specific model otherwise that will not have access of that module.

**Comment by sanket-hv** [comment]
> 
> 
> hello brother, Could you do me a favor? I will know, what this application is?
> and what is "flgIsAccess" in your MySQL database?

Yes, This app is basically for production management based on the different production unit.

This application is having role-based authentication and have different module...So the flgIsAccess value is 1 then that users have access to that specific model otherwise that will not have access of that module.

**Comment by rizalamhadi** [comment]
thank you for your answer, very clear. so a user can access a module with a value of flglsAccess 1 and other users who have a value 0 of flglsAccess cannot access the module. Right?
well, I have homework at my school and my job is to create a single page application with Reactjs also with backend nodejs. Can I use this project for my homework references?

**Comment by sanket-hv** [comment]
I recommend you to take reference only not for the copy paste. Try to take
reference from it and take good things from that. And develop the new one
by your own.

**Comment by rizalamhadi** [comment]
yeah of course
